Домашнее задание на 09.04.2022: миграции баз данных
TotsamyAS/totsamigram pull request #2
Opened 2022-04-02 19:48 UTC by TotsamyAS

+ по сравнениө с лекцией у меня больше полей считывается в базу данных

-возникла проблема с чтением даты из Birthday - почему-то не воспринимается информация оттуда, когда я хочу её перенести в user_information
помогите с этим, пожалуйста

2022-04-03 00:33 UTC, LazyTechwork requested changes

2022-04-03 00:33 UTC, LazyTechwork commented on app/Http/Controllers/MainController.php
> +        'password'=>Hash::make($request->get('password'))
Форматируйте код, читать становится сложно. Сочетание клавиш в PHPStorm: Ctrl+Alt+L

2022-04-03 00:33 UTC, LazyTechwork commented on resources/views/test-view-1.blade.php
> +<?= echo'<br> This is test view 1';
В Blade файлах не нужно делать echo, это обычный HTML, но с возможностью использовать PHP.
```suggestion
<br> This is test view 1
```

2022-04-03 00:33 UTC, LazyTechwork commented on resources/views/test-view-2.blade.php
> +<?= echo'<br> This is test view 1';
Аналогично

2022-04-03 00:33 UTC, LazyTechwork commented on resources/views/welcome.blade.php
> +</script>
Зачем?

2022-04-03 00:33 UTC, LazyTechwork commented on routes/web.php
> +Route::get('test_view_2', [MainController::class,'test_view_2_method']);*/
Незачем хранить это в комментариях, удаляйте.

2022-04-03 00:33 UTC, LazyTechwork commented
В плане не читается информация из birthday?

2022-04-03 08:36 UTC, TotsamyAS commented
> В плане не читается информация из birthday?

да, у меня почему-то там всегда "null" записывается, хотя я вроде бы сделал всё, как вы показывали...

2022-04-03 08:39 UTC, TotsamyAS commented on resources/views/test-view-1.blade.php
> +<?= echo'<br> This is test view 1';
> В Blade файлах не нужно делать echo, это обычный HTML, но с возможностью использовать PHP.

А может быть лучше вообще эти test_view уже удалить?
я просто думал, что в первом дз надо самому создать какие-то новые view, а не просто создавать такой же код, как и был на лекции...

2022-04-11 05:08 UTC, LazyTechwork commented
> > В плане не читается информация из birthday?
> 
> да, у меня почему-то там всегда "null" записывается, хотя я вроде бы сделал всё, как вы показывали...

Я тут у вас вообще не вижу миграции с информацией о пользователе

2023-09-17 18:49 UTC, closed without merging